apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - devops-app

  selector:
    matchLabels:
      app.kubernetes.io/name: backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s
